Update .net Framework 4.8
GKotfis/Log4NetWebViewer pull request #1
Opened 2022-02-11 22:05 UTC by Yako0b

Updated project and dependecies to .net Framework 4.8 to make is usable with VS 2022.

2022-02-14 15:44 UTC, GKotfis requested changes
Just requested one small changes (remove empty lines). Everything else looks good to me 👍

2022-02-14 15:44 UTC, GKotfis commented on Log4NetWebViewer/Services/WebService.cs
> +
Please remove unnecessary empty lines

2022-02-15 07:51 UTC, Yako0b commented
Empty lines were removed!

2022-02-15 11:23 UTC, GKotfis approved these changes

2022-02-15 11:24 UTC, merged

2022-02-15 11:25 UTC, GKotfis commented
Thank @Yako0b 🎉